### PR TITLE
Fix getActionEndpoint when null

### PR DESCRIPTION
**Pull request by Nightbr**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

For example for logout, if you set logout: { endpoint: null, }, but you have a baseEndpoint, it will execute DELETE {baseEndpoint}/null on your api. This will fix the thing.

### CODE REVIEW

**Comment by nnixaa** [comment]
Hi @Nightbr, thanks for you PR! We are in process of creating tests for auth so will be able to accept changes after we complete the tests.

**Comment by nnixaa** [comment]
Hi @Nightbr, we now have unit tests for the auth service, do you think you can add a test for this case?

**Comment by Nightbr** [comment]
Hey, I will try to add a test for this case.
Is all auth tests are in the file https://github.com/akveo/nebular/blob/master/src/framework/auth/services/auth.spec.ts?

**Comment by Nightbr** [comment]
I think this test already test the logout:
https://github.com/akveo/nebular/blob/master/src/framework/auth/services/auth.spec.ts#L294
I just add 3 lines to return null when actionEndpoint is null and don't return 'baseApiUrl/undefined'.
I don't think this need another test to the base test.
Let me know what do you think.

**Comment by eeskildsen** [comment]
This would be useful. I'm directing it to a dummy endpoint in the meantime.

**Comment by nnixaa** [comment]
Thanks @Nightbr, closing in favor of https://github.com/akveo/nebular/pull/1211

**Pull request closed without merging**
