### PR TITLE
fix(docs): add context-menu item click handler example

### LINKED ISSUE #265: Docs: add example how to handle click on context menu
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description
Subj.

### PR DESCRIPTION
**Pull request by Tibing**
### Please read and mark the following check list before creating a pull request:

 - [] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:
fix #265

### CODE REVIEW

**Comment by liganggang** [comment]
Hello, according to your steps, failed to solve the problem

**Comment by liganggang** [comment]
Is it related to version？ with 
Documentation is also not clear enough

**Comment by Tibing** [comment]
Hi @liganggang , could you please share your code? And what is the problem?

**Comment by idchlife** [comment]
Example does not clarify what "filter" function is used.

Also @Tibing, maybe the problem is the same as mine.
It actually does not work. 

default

default

**Comment by umarkashmiri** [comment]
I did a workaround to create a component and implement my logic there and added a link to that component. e.g in your case, you need to log out. create a logout component and change your nbcontextMenu= "items"

items: [{title:"logout". link:"/logout"}]

**Comment by jerasotin** [comment]
@nnixaa 
Hi
Can you help me?
I got a issue to control the margin property of menu title of nb-menu.
How to fix it?

**Pull request merged**
