### PR TITLE
fix(menu): highlight when active anchors

### LINKED ISSUE #875: NbMenuItem is not applied 'active' styles if fragments are used in URL
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report

### Issue description

**Current behavior:**
It appears that 'active' state is set to the first NbMenuItem if the URL contains a fragment - #something. My understanding is that 'pathMatch' property is setting the first matching NbMenuItem in the menu as 'selected' on every URL change, so no matter what you chose in the menu - the top item will always get 'active' styles applied.

**Expected behavior:**
'active' styles are toggled per NbMenuItem selected

**Steps to reproduce:**
My sub-menu contains the items that link to the following:
/pages/report/f75287ea1ed31a56cd912a6c86333b9cd4bcb852#top
/pages/report/f75287ea1ed31a56cd912a6c86333b9cd4bcb852#findings
/pages/report/f75287ea1ed31a56cd912a6c86333b9cd4bcb852#conclusion
/pages/report/f75287ea1ed31a56cd912a6c86333b9cd4bcb852#metadata

Clicking on any of the items will update URL and do other business logic, but will not set the selected item styles to 'active'.

peek 2018-10-08 23-19

**NOTE** this problem does not exist in ngx-admin demo, but sub-menu there links to URLs that do not use fragments.

**Related code:**
Not sure how relevant this piece is, but that's how NbMenuItem is created in my code.

```
const navigationItem = {
      title: itemName,
      icon: itemIcon,
      hidden: false,
      link: `/pages/report/${itemPath}`,
      fragment: itemFragment,
    }
```

### Other information:

```
npm: 6.0.1
node: v10.11.0
OS: Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Browser: Chrome, Firefox
```

**Angular, Nebular**
```
"@angular/core": "^6.1.9",
"@nebular/auth": "^2.0.1",
"@nebular/bootstrap": "^2.0.1",
"@nebular/security": "^2.0.1",
```

### PR DESCRIPTION
**Pull request by Tibing**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
#### Short description of what this resolves:

Closes #875

### CODE REVIEW

**Comment by Tibing** [comment]
Let's keep it opened until #1041 will be resolved. I have some ideas on how to completely solve this challenge but we can't be sure that all the things work fine without tests.

**Comment by Tibing** [comment]
Let's write regression tests for *NbMenuComponent*. Which verify that fragment selection works properly.

**Comment by nnixaa** [comment]
@yggg tests are failing :(

**Comment by yggg** [comment]
I've fixed unit tests but looks like something is wrong with browser stack tunnel.

**Pull request merged**
