### PR TITLE
feat(menu): support more navigation extras

### LINKED ISSUE #1914: NbMenuItem: support `queryParamsHandling`
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
Query Params are overriden.

**Expected behavior:**
I need to set `queryParamsHandling` to `merge`, so query params are not overriden, but merged.

**Related code:**

I need the following to work:

```
{
   title: 'title',
   link: 'search',
   queryParams: { query: 'title' },
   queryParamsHandling: 'merge' // this is not yet supported
} as NbMenuItem
```

### PR DESCRIPTION
**Pull request by kdubb**
This includes the`queryParamsHandling` & `preserveFragment` navigation extras options in addition to the already existing options.

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

Allows using the mentioned navigation extra parameters from menu item links.
Fixes #1914

### CODE REVIEW

**Comment by kdubb** [comment]
Fixes #1914

**Comment by kdubb** [comment]
@yggg Can you review and/or merge this?  It's quite helpful 😉

**Review by yggg — APPROVED** [review]

**Comment by yggg** [comment]
Thanks for the contribution @kdubb! Could you please check *"Allow edits by maintainers"* checkmark? You can find it here:
image
I need to merge master into your branch and check the PR with the latest changes from the master branch, but I can't do it without *"Allow edits by maintainers"* permission.

**Comment by kdubb** [comment]
@yggg I am familiar with the feature but oddly I have no "Allow edits by maintainers" checkbox on this specific PR.  Looking into why.

**Comment by kdubb** [comment]
I do not understand why the option is not available; I updated to HEAD of master for you instead.

**Pull request merged**
