### PR TITLE
feat(auth): field errors

### PR DESCRIPTION
**Pull request by eugenzor**
Add a possibility to add field errors (for backend validation purposes) like this:
selection_274

Also, there is an auth provider for Django Rest Auth:
https://django-rest-auth.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by nnixaa** [comment]
Hey @eugenzor, this is impressive and looks like a lot of work! Will review it soon.

**Comment by nnixaa** [comment]
This only thing is that we are now in process of refactoring of some auth code (like renaming provider to strategy and changing the token flow), so it your PR might require additional refactoring. Hope it's okay!

**Comment by eugenzor** [comment]
Hi @nnixaa 
yes, I'll do it, but a little bit later, when I have more time

**Comment by nnixaa** [comment]
@eugenzor cool!

**Pull request closed without merging**
