### PR TITLE
feat: update to angular 14.1.x

### PR DESCRIPTION
**Pull request by robgor3**
### Please read and mark the following check list before creating a pull request:

- [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.

#### Short description of what this resolves:
Following requests from gh issues (https://github.com/akveo/nebular/issues/3121, https://github.com/akveo/nebular/issues/3078, https://github.com/akveo/nebular/issues/3073) and after discussing it with tech leads at [hogs.live](https://hogs.live) we've decided to contribute this update to Nebular repo to unlock Angular update for us and other teams using Nebular.

**What have been done:**

Update to Angular 14.1.x
Update other packages to match Angular 14.1.x
Update to Boostrap 5, update to ng-bootrap 13.1.0

I haven't updated Angular to the newest 14.x.x version, since it requires typescript update to 4.8.x
Typescript v4.8.x have some deprecations that are causing issues in few `dev-schematics/utils` files.
Since I don't have much experience with low level typescript operations, I've decided not to interfere with these files.

This PR allows other project that are dependant on nebular to be upgraded to the newest Angular version.

### CODE REVIEW

**Comment by robgor3** [comment]
@azaiko-akveo @elupanov @yggg 
hi guys, could you give your opinion about this PR? is there any way this can be moved forward?

**Comment by elupanov** [comment]
> @azaiko-akveo @elupanov @yggg hi guys, could you give your opinion about this PR? is there any way this can be moved forward?

Hi @robgor3
Thank you for your PR. We also were working on Angular update and going to double check change with your PR.
The new release will be soon.

**Comment by gmadajczak** [comment]
@elupanov When we can expect the changes?

**Comment by elupanov** [comment]
> @elupanov When we can expect the changes?

I guess during the next 2 weeks

**Comment by niklasravnsborg** [comment]
Angular 15 was just released a few weeks ago. @elupanov Can we expect Nebular to support it soon?

**Comment by denStrigo** [comment]
related to https://github.com/akveo/nebular/pull/3143

**Comment by andreaslarssen** [comment]
How's it looking for an Angular 14 update? Seems like it's taking more than those two weeks?

**Comment by elupanov** [comment]
> How's it looking for an Angular 14 update? Seems like it's taking more than those two weeks?

We are really sorry. It took longer then we expected.
A new version with Angular 14.2.x just released.
https://github.com/akveo/nebular/releases/tag/v10.0.0

Thanks to @robgor3 and @denStrigo

**Comment by andreaslarssen** [comment]
Nice! Any guestimate on Angular 15 support?

**Comment by elupanov** [comment]
> Nice! Any guestimate on Angular 15 support?

It's hard to say. I would say it will be Q1 2023

**Pull request closed without merging**
