### PR TITLE
fix(themes): fix typo in layout style

### PR DESCRIPTION
**Pull request by JGreenlee**
add space on line 99

previously missing space caused themes to malfunction, if whitespace sensitive during packing

### CODE REVIEW

**Review by Azuka — APPROVED** [review]
Related to #3100

**Review by CrackerakiUA — APPROVED** [review]

**Review by chrisstoy — APPROVED** [review]

**Review by krzysztof-raciniewski — APPROVED** [review]
compile-error

This change fixes this error in Angular 14. Good job.

**Review by krzysztof-raciniewski — APPROVED** [review]

**Comment by ewalddieser** [comment]
When will this be merged? Looks like a no brainer.

**Review by flixd00 — APPROVED** [review]

**Comment by jgomesmv** [comment]
Related with #3078

**Review by wakonp — APPROVED** [review]
perfect - will fix it

**Comment by Lobaton2020** [comment]
My advice is modify the file directly while the PR is accepted to update the library version.
image
Thank you for your support guys

**Review by Caxvalencia — APPROVED** [review]

**Review by sengirab — APPROVED** [review]

**Comment by sengirab** [comment]
> My advice is modify the file directly while the PR is accepted to update the library version. image Thank you for your support guys

Can confirm this will work :), well, locally.. I would like deploy too ^^ this is blocking.

**Comment by sengirab** [comment]
@Tibing :)

**Comment by sengirab** [comment]
Since i don't know when this will be merged, and i need it now for a deploy, i figured out a way to get this fixed properly until this has been merged:

`npm i patch-package`

```
"scripts": {
    "postinstall": "patch-package"
}
```

Open up `node_modules/@nebular/theme/components/layout/_layout.component.theme.scss` and add a space to line `:99` like this: `@media screen and (min-width: $layout-window-mode-max-width + 150px) {`

Now generate a patch file for "patch-package": `npx patch-package @nebular/theme`.

Every npm install the fix will be patched :)

Cheers!

**Review by denStrigo — APPROVED** [review]

**Comment by flixd00** [comment]
When will the new version including this one be available?

**Pull request merged**
