### PR TITLE
Support hidden property

### LINKED ISSUE #30: NbMenuItem - Hidden property don't work ?
```typescript
{
  title: 'Users',
  link: '/pages/users',
  icon: 'ion-person',
  hidden: true
 }
```
The "Users" menu item still appears despite of the "hidden" property.

### PR DESCRIPTION
**Pull request by Xstoudi**
Fix #30

### CODE REVIEW

**Comment by lexzhukov** [comment]
@Xstoudi thanks

**Comment by darklinki** [comment]
I have done the changes manually in my ngx-admin project but its strangly not working. Do I have to do something different for ngx ?

**Comment by nnixaa** [comment]
Hey @darklinki, could you provide more details?

**Comment by nnixaa** [comment]
Hey @darklinki, could you provide more details?

**Comment by darklinki** [comment]
@nnixaa 

Sure,
I changed under node_modules/@nebular/theme/components/menu/menu-item.component.html
exactly like #30

Cleared npm cache and run the project with some menu items changed to hidden: true

The menu items are still shown.

**Comment by nnixaa** [comment]
@darklinki the html file you are changing isn't being used in the built version of the module. So the only option to make this change in your local installation is to checkout Nebular separately and connect it to your project with `npm link` till this change is published in the new version.

**Comment by darklinki** [comment]
@nnixaa 
Ty will try it

**Pull request merged**
