### PR TITLE
fix(tabset): hovering a tab doesn't affect the other tabs (#540)

### PR DESCRIPTION
**Pull request by cmajsmith**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:
This is a fix for #540 issue.

### CODE REVIEW

**Comment by nnixaa** [comment]
Hey @cmajsmith, thanks for the pr! I'm trying to match the description with the PR code, could you please elaborate how this is working? Thanks.

**Comment by nnixaa** [comment]
@cmajsmith ah, now I see it, thanks for the explanation! Is this a cross-browser way of fixing such issues?

**Comment by cmajsmith** [comment]
@nnixaa, you're warmly welcome. I didn't test in all the browsers, but **Can I use** says: [Yes!](https://caniuse.com/#feat=css-gencontent)

**Comment by nnixaa** [comment]
Hey @cmajsmith, got it. Though I personally feel like this is a bit fragile solution, and can be easily broken. Moreover, we have to introduce a new element in the dom, which is not particularly hidden.
What if we replace the `bold` font with a `text-shadow` instead? Like the second solution here https://www.sitepoint.com/quick-tip-fixing-font-weight-problem-hover-states/. We can even use the `currentColor` css value to not repeat the `color` in the shadow declaration. What do you think?

**Comment by cmajsmith** [comment]
Hi, @nnixaa! 

I've considered using the solution you've provided before settling with the one I've applied. The problem with `text-shadow` is that it inevitably adds blur to the text and it looks rather ugly. 

To be honest, I think both (that `text-shadow` one and one in this PR) solutions are _hacky_. And thinking about the nature of the issue and ways to solve it I more and more get convinced that the best solution is... to get rid of bold styling for `:hover` state. 

Assuming the inactive and unhovered tab is pale and becomes darker on hover - the control response will be enough to be noticed. The shift of neighboring tabs on click (caused with active tab turning into bold) will still occur, but it won't be as noticeable as on `:hover`. The question here is: does it align with your team's design guidelines? If it is - that would be cleanest fix ever. What do you think?

**Comment by nnixaa** [comment]
@cmajsmith I completely agree with you, let me check with the design team.

**Comment by nnixaa** [comment]
Hey @cmajsmith, we discussed this and agreed that we can remove `bold` font-weight from the `:hover` state. However, we need to do this in both tabs components (tabset and route-tabset). Would you like to complete this PR considering this?

**Comment by cmajsmith** [comment]
@nnixaa sure! I'll do it tomorrow once will have some time on my hands. Will update this PR once done.

**Comment by cmajsmith** [comment]
@nnixaa, seems like that is it.

**Comment by cmajsmith** [comment]
@nnixaa, it is still used for making active tab (both in tabset and route-tabset) bold. Bold was removed for hover only.

**Comment by nnixaa** [comment]
@cmajsmith exactly! Merging then.

**Comment by cmajsmith** [comment]
Hurray! Thanks @nnixaa for your time and help :)

**Pull request merged**
